---
- name: "Create directory {{ EXTRACT_VICEDATA_TARGET_DIR }}"
  file:
    path: "{{ EXTRACT_VICEDATA_TARGET_DIR }}"
    state: directory
    mode: '0755'
       
- name: Install python3 pip and other libs
  apt:
    pkg:
    - python3-pip 
    - libxcb-util-dev
    state: present
  become: true

- name: Ensure boto and boto3 modules are installed
  pip:
    name: ['boto3', 'botocore']


- name: 'Create softlink to libxcb-util.so.0'
  file:
    src: /lib/x86_64-linux-gnu/libxcb-util.so.1
    dest: /lib/x86_64-linux-gnu/libxcb-util.so.0
    state: link
  become: true

- name: Download VSCode
  get_url:
    url: "{{ DOWNLOAD_VICE_URL }}"
    validate_certs: no
    dest: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"

- name: "Extract {{ DOWNLOAD_VSCODE_ARCHIVE }} into {{ TOOLS_DIR }}"
  unarchive:
    src: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"
    dest: "{{ TOOLS_DIR }}"
    list_files: yes
  register: vscode_contents

- name: "Create VSCode symlink - {{ TOOLS_DIR }}/{{ vscode_contents.files[0] | dirname }} "
  file:
    src: "{{ TOOLS_DIR }}/{{ vscode_contents.files[0] | dirname }}"
    dest: "{{ SYMLINK }}"
    state: link

- name: Add VSCode and C64Debugger to PATH
  lineinfile:
    path: ~/shellenv.sh
    line: "export PATH=$PATH:$TOOLS_DIR/vscode/bin:$TOOLS_DIR/C64Debugger"
    state: present
    insertbefore: "# END ANSIBLE MANAGED BLOCK"

- name: Cleanup vscode download
  file:
   path: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"
   state: absent

#- name: Install Python Dependencies 
#  apt:
#    pkg:
#    - python-boto3
#    - python-boto
#    - python-botocore
#    state: present
#  become: true

- name: Install compiler and vice
  apt:
    pkg:
    - cc65
    - cc65-doc
    - vice
    - acme
    state: present
  become: true

- name: Download c64 debugger
  get_url:
    url: http://csdb.dk/getinternalfile.php/174330/C64Debugger-v0.64.56-linux-x64.tar.gz 
    dest: '{{ TOOLS_DIR }}/C64Debugger-v0.64.56-linux-x64.tar.gz'

- name: Extract C64Debugger
  unarchive:
    src: '{{ TOOLS_DIR }}/C64Debugger-v0.64.56-linux-x64.tar.gz'
    dest: '{{ TOOLS_DIR }}'

- name: Download vice-data from S3
  get_url:
    url: https://rodoherty1-vice-data.s3.eu-west-1.amazonaws.com/vice-data.tar.gz 
    validate_certs: no
    dest: '{{ DOWNLOAD_VSCODE_ARCHIVE }}'

- name: Extract vice-data.tar.gz
  unarchive:
    src: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"
    dest: "{{ EXTRACT_VICEDATA_TARGET_DIR }}"
    list_files: yes
  register: archive_contents

#- name: "Create TMP dir"
#  file:
#    path: "{{ TOOLS_DIR }}/myTemp"
#    state: directory
#    mode: '0755'
   
- name: Copy vice-data contents to /usr/lib/vice
  copy:
    src: "{{ EXTRACT_VICEDATA_TARGET_DIR }}/data/"
    dest: /usr/lib/vice
    remote_src: yes
  become: true

#- name: Copy vice-data contents to /usr/lib/vice
#  copy:
#    src: "{{ EXTRACT_VICEDATA_TARGET_DIR }}/data/"
#    dest: "{{ TOOLS_DIR }}/myTemp"
#    remote_src: yes
#  become: true

- name: 'Cleanup downloaded archives'
  file: 
    path: '{{ item }}' 
    state: absent
  with_items:
    - '{{ EXTRACT_VICEDATA_TARGET_DIR }}' 
    - '{{ TOOLS_DIR }}/C64Debugger-v0.64.56-linux-x64.tar.gz'
    - '{{ DOWNLOAD_VSCODE_ARCHIVE }}'

- name: Git clone acme-assembly-vscode-template
  git:
    repo=https://github.com/Esshahn/acme-assembly-vscode-template
    dest='{{ WORKSPACE_DIR }}/acme-assembly-vscode-template'

- name: Git clone OldSkoolCoder tutorials
  git:
    repo=https://github.com/rodoherty1/6502-Examples
    dest='{{ WORKSPACE_DIR }}/6502-Examples'

- name: "Create CC65 c64-adm.cfg link"
  file:
    src: /usr/share/cc65/cfg/c64-asm.cfg
    dest: '{{ WORKSPACE_DIR }}/6502-Examples/c64-adm.cfg'
    state: link

#- name: Copy acme build files to OldSkoolCoder folder
#  copy:
#    src: '{{ WORKSPACE_DIR }}/acme-assembly-vscode-template/{{ item }}'
#    dest: '{{ WORKSPACE_DIR }}/oldskoolcoder'
#    remote_src: yes
#  with_items: 
#    - .vscode
#    - bin
#    - build

- name: Install Visual Studio Code extension - TonyLandi.acmecrossassembler
  command: '{{ SYMLINK }}/bin/code --install-extension TonyLandi.acmecrossassembler'

- name: Install Visual Studio Code extension - rosc.vs64
  command: '{{ SYMLINK }}/bin/code --install-extension rosc.vs64'

- name: Install Visual Studio Code extension - tlgkccampbell.code-ca65 
  command: '{{ SYMLINK }}/bin/code --install-extension tlgkccampbell.code-ca65'

