---
- name: "Create directory {{ EXTRACT_VICEDATA_TARGET_DIR }}"
  file:
    path: "{{ EXTRACT_VICEDATA_TARGET_DIR }}"
    state: directory
    mode: '0755'
   
- name: Install python3 pip
  apt:
    pkg:
    - python3-pip 
    state: present
  become: true

- name: Ensure boto and boto3 modules are installed
  pip:
    name: ['boto3', 'botocore']

- name: Download VSCode
  get_url:
    url: "{{ DOWNLOAD_VICE_URL }}"
    validate_certs: no
    dest: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"

- name: "Extract {{ DOWNLOAD_VSCODE_ARCHIVE }} into {{ TOOLS_DIR }}"
  unarchive:
    src: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"
    dest: "{{ TOOLS_DIR }}"
    list_files: yes
  register: vscode_contents

- name: C64 Logging
  debug:
    msg: "{{ vscode_contents.files[0] | dirname }}"

- name: "Create VSCode symlink - {{ TOOLS_DIR }}/{{ vscode_contents.files[0] | dirname }} "
  file:
    src: "{{ TOOLS_DIR }}/{{ vscode_contents.files[0] | dirname }}"
    dest: "{{ SYMLINK }}"
    state: link

- name: Add VSCode to PATH
  lineinfile:
    path: ~/shellenv.sh
    line: "export PATH=$PATH:$TOOLS_DIR/vscode/bin"
    state: present
    insertbefore: "# END ANSIBLE MANAGED BLOCK"

- name: Cleanup vscode download
  file:
   path: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"
   state: absent

- name: Install Python Dependencies 
  apt:
    pkg:
    - python-boto3
    - python-boto
    - python-botocore
    state: present
  become: true

- name: Install compiler and vice
  apt:
    pkg:
    - cc65
    - cc65-doc
    - vice
    state: present
  become: true

- name: Download vice-data from S3
  get_url:
    url: https://rodoherty1-vice-data.s3.eu-west-1.amazonaws.com/vice-data.tar.gz 
    validate_certs: no
    dest: '{{ DOWNLOAD_VSCODE_ARCHIVE }}'

- name: Extract vice-data.tar.gz
  unarchive:
    src: "{{ DOWNLOAD_VSCODE_ARCHIVE }}"
    dest: "{{ EXTRACT_VICEDATA_TARGET_DIR }}"
    list_files: yes
  register: archive_contents

#- name: "Create TMP dir"
#  file:
#    path: "{{ TOOLS_DIR }}/myTemp"
#    state: directory
#    mode: '0755'
   
- name: Copy vice-data contents to /usr/lib/vice
  copy:
    src: "{{ EXTRACT_VICEDATA_TARGET_DIR }}/data/"
    dest: /usr/lib/vice
    remote_src: yes
  become: true

#- name: Copy vice-data contents to /usr/lib/vice
#  copy:
#    src: "{{ EXTRACT_VICEDATA_TARGET_DIR }}/data/"
#    dest: "{{ TOOLS_DIR }}/myTemp"
#    remote_src: yes
#  become: true

- name: "Cleanup {{ EXTRACT_VICEDATA_TARGET_DIR }}"
  file: 
   path: "{{ EXTRACT_VICEDATA_TARGET_DIR }}" 
   state: absent

- name: "Remove {{ DOWNLOAD_VSCODE_ARCHIVE }}"
  file: 
   path: "{{ DOWNLOAD_VSCODE_ARCHIVE }}" 
   state: absent
 
- name: Git clone acme-assembly-vscode-template
  git:
    repo=https://github.com/Esshahn/acme-assembly-vscode-template
    dest='{{ WORKSPACE_DIR }}/acme-assembly-vscode-template'

- name: Git clone OldSkoolCoder tutorials
  git:
    repo=https://github.com/rodoherty1/Tutorials
    dest='{{ WORKSPACE_DIR }}/oldskoolcoder'

- name: Copy acme build files to OldSkoolCoder folder
  copy:
    src: '{{ WORKSPACE_DIR }}/acme-assembly-vscode-template/{{ item }}'
    dest: '{{ WORKSPACE_DIR }}/oldskoolcoder'
    remote_src: yes
  with_items: 
    - .vscode
    - bin
    - build


- name: Install Visual Studio Code extensions
  command: '{{ SYMLINK }}/bin/code --install-extension TonyLandi.acmecrossassembler'
