---
- name: 'Create {{ TOOLS_DIR }}'
  file:
    path: '{{ TOOLS_DIR }}'
    state: directory
    mode: '0755'

- name: Create ~/workspace
  file:
    path: ~/workspace
    state: directory
    mode: '0755'

- name: Install tree
  apt: 
    pkg: tree
    state: present

- name: Create "{{ shell_env_file }}"
  file:
      path: "{{ shell_env_file }}"
      state: touch
      mode: '0755'

- name: "Add environment variables and utils to {{ shell_env_file }}"
  blockinfile:
    path: "{{ shell_env_file }}"
    block: |
      ns() {
      mkcdir $NEW_SCRATCH_DIR
      touch $NEW_SCRATCH_DIR/scratch.txt
      } 

      mkcdir() {
      mkdir -p -- "$1" && cd -P -- "$1"
      }

- name: 'Add lines to {{ shell_env_file }}'
  lineinfile:
    path: '{{ shell_env_file }}'
    insertafter: 'BOF'
    line: '{{ item }}'
  with_items:
    - alias today='cd $NEW_SCRATCH_DIR'
    - alias vi='vim'
    - export TOOLS_DIR=~/tools
    - NEW_SCRATCH_DIR=~/scratch/$(date +%b%d)

- name: Add import shellenv to bashrc
  lineinfile:
    path: ~/.bashrc
    insertbefore: 'BOF'
    line: source {{ shell_env_file }}

- name: Create vimrc
  file:
      path: '/home/{{ ansible_user_id }}/.vimrc'
      state: touch
      mode: '0755'

- name: Add vimrc file
  lineinfile:
    path: '/home/{{ ansible_user_id }}/.vimrc'
    insertafter: 'BOF'
    line: '{{ item }}'
  with_items:
    - set number
    - set background=dark

      # Can I download from s3 is AWS_S3_BUCKET is set?
      #
#  - name: Download KDE Plasma config from S3
#    aws_s3:
#      bucket: "{{ AWS_S3_BUCKET }}"
#      object: /kde-config.tar.gz
#      dest: '/home/{{ ansible_user_id }}'
#      mode: get

#  - name: Extract KDE config
#    unarchive:
#      src: '/home/{{ ansible_user_id }}/kde-config.tar.gz'
#      dest: '/home/{{ ansible_user_id }}/'
#      list_files: yes
#    register: archive_contents

      # Add a cleanup step!
      #

- name: Install python3 pip and other libs
  apt:
    pkg:
    - python3-pip 
    state: present
  become: true

- name: Ensure pexpect is installed
  pip:
    name: ['pexpect']


