---
- name: Setup tools and workspace directories
  hosts: all
#  remote_user: "{{ ansible_user_id }}"
  
  tasks:
  - name: Create ~/tools
    file:
      path: ~/tools
      state: directory
      mode: '0755'

  - name: Create ~/workspace
    file:
      path: ~/workspace
      state: directory
      mode: '0755'


