---
- name: Download and Install Google Chrome
  hosts: all
  remote_user: {{ ansible_user_id }}
  become: true 
  vars: 
    WORKING_DIR: /tmp
    DOWNLOAD_ARCHIVE: "{{ WORKING_DIR }}/google-chrome-stable_current_amd64.deb"
    DOWNLOAD_URL: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  
  tasks:
  - name: Download Google Chrome
    get_url:
      url: "{{ DOWNLOAD_URL }}"
      validate_certs: no
      dest: "{{ DOWNLOAD_ARCHIVE }}"

  - name: Install chrome package
    apt:
      deb: "{{ DOWNLOAD_ARCHIVE }}"

  - name: Cleanup google chrome download
    file: 
     path: "{{ DOWNLOAD_ARCHIVE }}" 
     state: absent
