---
- name: Setup C64 Dev Environment
  hosts: all
  remote_user: "{{ ansible_user_id }}"
  become: false
  vars: 
    DOWNLOAD_TARGET_DIR: "/home/{{ ansible_user_id }}/tools"
    EXTRACT_TARGET_DIR: "{{ DOWNLOAD_TARGET_DIR }}/vice-data"
    DOWNLOAD_ARCHIVE: "{{ EXTRACT_TARGET_DIR }}/vscode.tar.gz"
    DOWNLOAD_URL: https://vscode-update.azurewebsites.net/latest/linux-x64/stable
    SYMLINK: "{{ DOWNLOAD_TARGET_DIR }}/vscode"
  
  tasks:
  - name: "Create directory {{ EXTRACT_TARGET_DIR }}"
    file:
      path: "{{ EXTRACT_TARGET_DIR }}"
      state: directory
      mode: '0755'
   
  - name: Install python3 pip
    apt:
      pkg:
      - python3-pip 
      state: present
    become: true

  - name: Ensure boto and boto3 modules are installed
    pip:
      name: ['boto3', 'botocore']

  - name: Download VSCode
    get_url:
      url: "{{ DOWNLOAD_URL }}"
      validate_certs: no
      dest: "{{ DOWNLOAD_ARCHIVE }}"

  - name: "Extract {{ DOWNLOAD_ARCHIVE }} into {{ DOWNLOAD_TARGET_DIR }}"
    unarchive:
      src: "{{ DOWNLOAD_ARCHIVE }}"
      dest: "{{ DOWNLOAD_TARGET_DIR }}"
      list_files: yes
    register: vscode_contents

#  - name: C64 Logging
#    debug:
#      msg: "{{ vscode_contents.files[0] | dirname }}"

  - name: "Create VSCode symlink - {{ DOWNLOAD_TARGET_DIR }}/{{ vscode_contents.files[0] | dirname }} "
    file:
      src: "{{ DOWNLOAD_TARGET_DIR }}/{{ vscode_contents.files[0] | dirname }}"
      dest: "{{ SYMLINK }}"
      state: link

  - name: Add VSCode to PATH
    lineinfile:
      path: ~/shellenv.sh
      line: "export PATH=$PATH:$TOOLS_DIR/vscode/bin"
      state: present
      insertbefore: "# END ANSIBLE MANAGED BLOCK"

  - name: Cleanup vscode download
    file:
     path: "{{ DOWNLOAD_ARCHIVE }}"
     state: absent

  - name: Install Python Dependencies 
    apt:
      pkg:
      - python-boto3
      - python-boto
      - python-botocore
      state: present
    become: true

  - name: Install compiler and vice
    apt:
      pkg:
      - cc65
      - cc65-doc
      - vice
      state: present
    become: true

  - name: Download vice-data from S3
    aws_s3:
      bucket: "{{ AWS_S3_BUCKET }}"
      object: /vice-data.tar.gz
      dest: '{{ DOWNLOAD_ARCHIVE }}'
      mode: get


  - name: Extract vice-data.tar.gz
    unarchive:
      src: "{{ DOWNLOAD_ARCHIVE }}"
      dest: "{{ EXTRACT_TARGET_DIR }}"
      list_files: yes
    register: archive_contents

#  - name: "Create TMP dir"
#    file:
#      path: "{{ DOWNLOAD_TARGET_DIR }}/myTemp"
#      state: directory
#      mode: '0755'
   
  - name: Copy vice-data contents to /usr/lib/vice
    copy:
      src: "{{ EXTRACT_TARGET_DIR }}/data/"
      dest: /usr/lib/vice
      remote_src: yes
    become: true

#  - name: Copy vice-data contents to /usr/lib/vice
#    copy:
#      src: "{{ EXTRACT_TARGET_DIR }}/data/"
#      dest: "{{ DOWNLOAD_TARGET_DIR }}/myTemp"
#      remote_src: yes
#    become: true

  - name: "Cleanup {{ EXTRACT_TARGET_DIR }}"
    file: 
     path: "{{ EXTRACT_TARGET_DIR }}" 
     state: absent

  - name: "Remove {{ DOWNLOAD_ARCHIVE }}"
    file: 
     path: "{{ DOWNLOAD_ARCHIVE }}" 
     state: absent
 

