---
- name: Setup tools and workspace directories
  hosts: all
  
  tasks:
  - name: 'Create {{ TOOLS_DIR }}'
    file:
      path: '{{ TOOLS_DIR }}'
      state: directory
      mode: '0755'

  - name: Create ~/workspace
    file:
      path: ~/workspace
      state: directory
      mode: '0755'


