---
DOWNLOAD_TARGET_DIR: "/home/{{ ansible_user_id }}/tools"
EXTRACT_TARGET_DIR: "{{ DOWNLOAD_TARGET_DIR }}/vice-data"
DOWNLOAD_ARCHIVE: "{{ EXTRACT_TARGET_DIR }}/vscode.tar.gz"
DOWNLOAD_URL: https://vscode-update.azurewebsites.net/latest/linux-x64/stable
SYMLINK: "{{ DOWNLOAD_TARGET_DIR }}/vscode"

