---
- name: Installing Zsh and git
  become: true
  apt: pkg=zsh state=latest
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig; fi
  when: installation|success
  sudo: no

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success
  sudo: no

#- name: change user shell to zsh 
#  become: yes
#  user:
#    name: "{{ the_user }}"
#    shell: /usr/bin/zsh

- name: Case insensitve password string match
  expect:
    command: "chsh -s /usr/bin/zsh"
    responses:
      (?i)password: "{{ my_password }}"
    #creates: ".shell_is_fish"
